/* pinHeck games: switch, lamp and output names for table scripts, one section per game.

   Domino's Spectacular Pinball Adventure (pinheck_dominos_*).
   Sources: Dominos-Switch-Matrix.pdf, Dominos-Lamp-Matrix.pdf and Spooky_Pinball_Domino's_Solenoid_List.pdf
   (Ken Layton, 2019). Not in them: User (2) and Back (5), the board's USER_0 and BACK inputs in the firmware's
   cabinet read order (design spec 2.2); the optos 95 (Center Ramp) and 96 (Oven Ramp), from the firmware's
   switch handlers (Plan 8b, Ruling 5). Numbering of the pinHeck driver (src/wpc/pinheck.c):
     matrix switch or lamp n (0-63)  (n / 8 + 1) * 10 + n % 8 + 1
     cabinet switch n                n (1-8), n + 82 (9-15)
     start button lamp               91
     coil n (0-23)                   solenoid n + 1
     GI_0..7, GI_8..15               solenoids 25-32, 37-44
     on-board RGB left R, G, B, right R, G, B    51-56 (0-255)
     servos 0-4                      57-61 (0-255: the game's pulse range, Domino's 1.0-2.0 ms)
     external RGB LED R, G, B        62-64 (0-255)
   A table presses the flipper buttons through PinMAME's flipper column, 114 (left) and 112 (right),
   which PinMAME copies to cabinet switches 4 and 3 every frame. Numbers not listed are unused.
   HandleMechanics bit 0 simulates the Noid (servo 0, closing Noid Home 58), bit 1 the target bank (servo 1);
   a table that moves them itself clears the bit.

   Rob Zombie's Spookshow International (pinheck_rzspook_*).
   Sources: RZ_Switch_Matrix_Production.pdf, RZ_Lamp_Matrix_Production.pdf and wiring-board-chart.png (coils, GI,
   servos); numbering as above. Not in them: User (2) and Back (5), as for Domino's. Servo levels 0-255 are
   0-180 degrees (0.544-2.4 ms). The LDG light (external RGB LED) gets red, blue, green on 62-64 while the
   service menu's SWAP G <-> B is NO, its factory setting. HandleMechanics bit 0 raises the drop target (48) on
   its coil, bit 1 closes the flippers' end-of-stroke switches while their coils are on.

   The Jetsons (pinheck_jetsons_*).
   Sources: Jetsons_Switch_Matrix_Production.pdf, Jetsons_Light_Matrix_Production.pdf and JETSONS-WIRE-TO-BOARD.pdf
   (coils, GI, optos); numbering as above, PinMAME numbers. A device is numbered where JET_V004 reads it: the
   kickout hole on 18 (the switch chart says 17), the trough's eject position on its opto 92 (the chart's Ball
   Trough 1, 52, is never read). The scoop opto (96) ejects the ball; the chart's Scoop switch (21) also fires
   the scoop coil, 3 s after it closes in a game. Not listed: switches 27, 28, 37, 38, 47, 48, 57 and 58, and
   lamps 66-68, which the firmware uses but no chart names. Servo levels 0-255 are 0-180 degrees (0.544-2.4 ms); servo 0
   is the Orbitty topper. The firmware never writes the external RGB LED (62-64). HandleMechanics bit 0 closes
   the flippers' end-of-stroke switches while their coils are on. */
#ifndef PINHECK_NAMES_H
#define PINHECK_NAMES_H

typedef struct { int num; const char *id; const char *name; } pinheck_name_t;

static const pinheck_name_t pinheck_dominos_switch_names[] = {
  {   1, "swCoinDoor",  "Coin Door (closed)" },
  {   2, "swUser",      "User" },
  {   3, "swRFlip",     "Right Flipper" },
  {   4, "swLFlip",     "Left Flipper" },
  {   5, "swBack",      "Back" },
  {   6, "swEnter",     "Enter (menu)" },
  {   7, "swCoin",      "Coin Mech" },
  {   8, "swTilt",      "Tilt" },
  {  11, "swShooter",   "Shooter Lane" },
  {  12, "swTrough1",   "Trough Ball 1" },
  {  13, "swTrough2",   "Trough Ball 2" },
  {  14, "swTrough3",   "Trough Ball 3" },
  {  15, "swRFlipEOS",  "Right Flipper EOS" },
  {  16, "swRSling",    "Right Sling" },
  {  17, "swRInlane",   "Right Inlane" },
  {  18, "swROutlane",  "Right Outlane" },
  {  21, "swLFlipEOS",  "Left Flipper EOS" },
  {  22, "swLSling",    "Left Sling" },
  {  23, "swLInlane",   "Left Inlane" },
  {  24, "swLOutlane",  "Left Outlane" },
  {  25, "swLScoop",    "Left Scoop" },
  {  26, "swBankR",     "Noid Bank Right" },
  {  27, "swBankM",     "Noid Bank Middle" },
  {  28, "swBankL",     "Noid Bank Left" },
  {  31, "swDelivery",  "Target Delivery" },
  {  32, "swQuality",   "Target Quality Check" },
  {  33, "swBake",      "Target Bake" },
  {  34, "swPrepare",   "Target Prepare" },
  {  35, "swOrder",     "Target Order Placed" },
  {  36, "swROrbit",    "Right Orbit" },
  {  37, "swRNoidOrb",  "Right Noid Orbit" },
  {  38, "swLNoidOrb",  "Left Noid Orbit" },
  {  41, "swStarLane",  "Star Lane" },
  {  42, "sw5Lane",     "5 Lane" },
  {  43, "swRPop",      "Right Pop Bumper" },
  {  44, "swLowerPop",  "Lower Pop Bumper" },
  {  45, "swLPop",      "Left Pop Bumper" },
  {  46, "swLOrbit",    "Left Orbit" },
  {  47, "swSpinner",   "Spinner" },
  {  48, "swRScoop",    "Right Scoop" },
  {  58, "swNoidHome",  "Noid Home" },
  {  94, "swStart",     "Start Button" },
  {  95, "swRampOpto",  "Opto (Center Ramp)" },
  {  96, "swOvenOpto",  "Opto (Oven Ramp)" },
  { 112, "swLRFlip",    "Right Flipper button (reaches switch 3)" },
  { 114, "swLLFlip",    "Left Flipper button (reaches switch 4)" },
  { 0 }
};

static const pinheck_name_t pinheck_dominos_lamp_names[] = {
  {  11, "lLetterO",           "O" },
  {  12, "lLetterV",           "V" },
  {  13, "lMystery",           "Mystery" },
  {  14, "lStartCareer",       "Start Career" },
  {  15, "lGoldFranny",        "Gold Franny" },
  {  16, "lFranchisee",        "Franchisee" },
  {  17, "lManager",           "Manager" },
  {  18, "lDriver",            "Driver" },
  {  21, "lOrderAgain",        "Order Again" },
  {  22, "lMakePizza",         "Make Pizza" },
  {  23, "lLostTopping",       "Lost Topping" },
  {  24, "lPizzaDispatch",     "Pizza Dispatch" },
  {  25, "lMegaWeek",          "Mega Week" },
  {  26, "lHandleTheRush",     "Handle The Rush" },
  {  27, "lLetterE",           "E" },
  {  28, "lLetterN",           "N" },
  {  31, "lLDominoOrbit",      "Left Domino Orbit" },
  {  32, "lLMakePizzaOrbit",   "Left Make Pizza Orbit" },
  {  33, "lLostToppingL",      "Lost Topping Left (Noid Orbit)" },
  {  34, "lTarget1",           "Target 1" },
  {  35, "lTarget2",           "Target 2" },
  {  36, "lTarget3",           "Target 3" },
  {  37, "lBattleNoidN",       "Battle Noid N" },
  {  41, "lLostToppingR",      "Lost Topping Right (Noid Orbit)" },
  {  42, "lRampPizzaDispatch", "Ramp Pizza Dispatch" },
  {  43, "lExtraBall",         "Extra Ball" },
  {  44, "lRampDomino",        "Ramp Domino" },
  {  45, "lOvenRampRush",      "Oven Ramp Rush" },
  {  46, "lOvenRampJackpot",   "Oven Ramp Jackpot" },
  {  47, "lOvenRampMegaWeek",  "Oven Ramp Mega Week" },
  {  48, "lTrackerGreen",      "Pizza Tracker Green Side" },
  {  51, "lDominoDotTop",      "Domino Dot Top" },
  {  52, "lDominoDotMiddle",   "Domino Dot Middle" },
  {  53, "lDominoDotBottomL",  "Domino Dot Bottom Left" },
  {  54, "lPizzaWars",         "Pizza Wars" },
  {  55, "lGlobalConquest",    "Global Conquest" },
  {  56, "lFastestPizzaMaker", "Fastest Pizza Maker" },
  {  57, "l5Lane",             "5 Lane" },
  {  58, "lStarLane",          "Star Lane" },
  {  61, "lOvenPizzaScoop",    "Oven Pizza Scoop" },
  {  62, "lMakePizzasROrbit",  "Make Pizzas Right Orbit" },
  {  63, "lOrderPlaced",       "Order Placed" },
  {  64, "lPrepare",           "Prepare" },
  {  65, "lBake",              "Bake" },
  {  66, "lQualityCheck",      "Quality Check" },
  {  67, "lDelivery",          "Delivery" },
  {  68, "lTrackerBlue",       "Pizza Tracker Blue Side" },
  {  91, "lStart",             "Start Button" },
  { 0 }
};

/* solenoid outputs: coils, GI strings, RGB channels and servos */
static const pinheck_name_t pinheck_dominos_solenoid_names[] = {
  {  1, "sKnocker",    "Knocker (optional)" },
  {  2, "sShaker",     "Shaker Motor (optional)" },
  {  3, "sLowerPop",   "Lower Pop Bumper" },
  {  4, "sLPop",       "Left Pop Bumper" },
  {  5, "sRPop",       "Right Pop Bumper" },
  {  6, "sMagnet",     "Magnet Coil" },
  {  7, "sPost",       "Up Post" },
  {  9, "sLScoop",     "Left Scoop" },
  { 10, "sLFlipHigh",  "Left Flipper High Center (power)" },
  { 11, "sLSling",     "Left Slingshot" },
  { 12, "sLFlipLow",   "Left Flipper Low (hold)" },
  { 13, "sRScoop",     "Right Scoop" },
  { 17, "sLaunch",     "Auto Launcher" },
  { 18, "sLoad",       "Ball Trough" },
  { 19, "sRFlipLow",   "Right Flipper Low (hold)" },
  { 20, "sRSling",     "Right Slingshot" },
  { 21, "sRFlipHigh",  "Right Flipper High Center (power)" },
  { 25, "sGI0",        "GI_0 (backbox)" },
  { 26, "sGI1",        "GI_1 (backbox)" },
  { 27, "sGI2",        "GI_2 (backbox)" },
  { 28, "sGI3",        "GI_3 (backbox)" },
  { 29, "sGI4",        "GI_4 (backbox)" },
  { 30, "sGI5",        "GI_5 (backbox)" },
  { 31, "sGI6",        "GI_6 (backbox)" },
  { 32, "sGI7",        "GI_7 (backbox)" },
  { 37, "sGI8",        "GI_8 (playfield)" },
  { 38, "sGI9",        "GI_9 (playfield)" },
  { 39, "sGI10",       "GI_10 (playfield)" },
  { 40, "sGI11",       "GI_11 (playfield)" },
  { 41, "sGI12",       "GI_12 (playfield)" },
  { 42, "sGI13",       "GI_13 (playfield)" },
  { 43, "sGI14",       "GI_14 (playfield)" },
  { 44, "sGI15",       "GI_15 (playfield)" },
  { 51, "sRGB1R",      "RGB1 (left) red" },
  { 52, "sRGB1G",      "RGB1 (left) green" },
  { 53, "sRGB1B",      "RGB1 (left) blue" },
  { 54, "sRGB2R",      "RGB2 (right) red" },
  { 55, "sRGB2G",      "RGB2 (right) green" },
  { 56, "sRGB2B",      "RGB2 (right) blue" },
  { 57, "sNoid",       "Servo 0: Noid (continuous rotation)" },
  { 58, "sBank",       "Servo 1: target bank" },
  { 59, "sServo2",     "Servo 2" },
  { 60, "sServo3",     "Servo 3" },
  { 61, "sServo4",     "Servo 4" },
  { 62, "sExtR",       "External RGB LED red" },
  { 63, "sExtG",       "External RGB LED green" },
  { 64, "sExtB",       "External RGB LED blue" },
  { 0 }
};

static const pinheck_name_t pinheck_rzspook_switch_names[] = {
  {   1, "swCoinDoor",  "Coin Door (closed)" },
  {   2, "swUser",      "User" },
  {   3, "swRFlip",     "Right Flipper" },
  {   4, "swLFlip",     "Left Flipper" },
  {   5, "swBack",      "Back" },
  {   6, "swEnter",     "Enter (menu)" },
  {   7, "swCoin",      "Coin Mech" },
  {   8, "swTilt",      "Tilt" },
  {  11, "swShooter",   "Shooter Lane" },
  {  12, "swTrough1",   "Trough 1" },
  {  13, "swTrough2",   "Trough 2" },
  {  14, "swTrough3",   "Trough 3" },
  {  15, "swTrough4",   "Trough 4" },
  {  16, "swTrough5",   "Trough 5" },
  {  17, "swTrough6",   "Trough 6" },
  {  18, "swTrough7",   "Trough 7" },
  {  21, "swROutlane",  "Right Out Lane" },
  {  22, "swRInlane",   "Right In Lane" },
  {  23, "swRSling",    "Right Lower Sling" },
  {  24, "swRFlipEOS",  "Right Flip EOS" },
  {  25, "swLFlipEOS",  "Left Flip EOS" },
  {  26, "swLSling",    "Left Lower Sling" },
  {  27, "swLInlane",   "Left In Lane" },
  {  28, "swLOutlane",  "Left Out Lane" },
  {  31, "swExtraBall", "Extra Ball" },
  {  32, "swRUSling",   "Right Upper Sling" },
  {  33, "swRailLow",   "Right Rail Lower" },
  {  34, "swRailUp",    "Right Rail Upper" },
  {  35, "swRInner",    "Right Inner Orbit" },
  {  36, "swRPop",      "Right Pop Bumper" },
  {  37, "swChicken",   "Left Upper Playfield (Chicken)" },
  {  38, "swGasoline",  "Right Upper Playfield (Gasoline)" },
  {  41, "swUFlipEOS",  "Upper Flipper EOS" },
  {  42, "swROrbit",    "Right Outer Orbit" },
  {  43, "swVUK",       "VUK" },
  {  44, "swSecret",    "Secret Passage" },
  {  45, "swLInner",    "Left Inner Orbit" },
  {  46, "swRLDG",      "Right Living Dead Girl" },
  {  47, "swLLDG",      "Left Living Dead Girl" },
  {  48, "swDrop",      "Drop Target (down)" },
  {  51, "swRampTgt",   "Ramp Target" },
  {  52, "swRattle",    "Right Rattle Switch" },
  {  54, "swLLPop",     "Lower Left Pop" },
  {  55, "swULPop",     "Upper Left Pop" },
  {  56, "swPopTarget", "Pop Target" },
  {  57, "swLUSling",   "Left Upper Sling" },
  {  58, "swLOrbit",    "Left Orbit" },
  {  61, "swRamp",      "Ramp" },
  {  94, "swStart",     "Start Button" },
  {  95, "swGateOpto",  "Upper PF Opto Spaulding (gate)" },
  {  96, "swExitOpto",  "Upper PF Opto (exit)" },
  { 112, "swLRFlip",    "Right Flipper button (reaches switch 3)" },
  { 114, "swLLFlip",    "Left Flipper button (reaches switch 4)" },
  { 0 }
};

static const pinheck_name_t pinheck_rzspook_lamp_names[] = {
  {  11, "lRockAgain",         "Rock Again" },
  {  12, "lLDG",               "LDG" },
  {  13, "lRedHot",            "Red Hot" },
  {  14, "lDragula",           "Dragula" },
  {  15, "lHouse100K",         "House 100K" },
  {  16, "lSuperBeast",        "Super Beast" },
  {  17, "lDeadCityRadio",     "Dead City Radio" },
  {  18, "lMurderRide",        "Murder Ride" },
  {  21, "lWhat",              "What" },
  {  22, "lDemonoid",          "Demonoid Phen" },
  {  23, "lAmerWitch",         "Amer. Witch" },
  {  24, "lHellBound",         "Hell Bound" },
  {  25, "lExtraBall",         "Extra Ball" },
  {  26, "lNum3",              "3" },
  {  27, "lLetterO",           "O" },
  {  28, "lLetterP",           "P" },
  {  31, "lSkillShot2",        "Skill Shot 2" },
  {  32, "lGein",              "Gein" },
  {  33, "lFish",              "Fish" },
  {  34, "lDrSatan",           "Dr. Satan" },
  {  35, "lInnerRightArrow",   "Inner Right Arrow" },
  {  36, "lRightOrbitArrow",   "Right Orbit Arrow" },
  {  37, "lTopX",              "Top X" },
  {  38, "lBottomX",           "Bottom X" },
  {  41, "lLetterC",           "C" },
  {  42, "lLetterH",           "H" },
  {  43, "lSkillShot1",        "Skill Shot 1" },
  {  44, "lNum1",              "1" },
  {  45, "lHurryUp",           "Hurry Up" },
  {  46, "lVideoMode",         "Video Mode" },
  {  47, "lModeStart",         "Mode Start" },
  {  48, "lLeftOrbitArrow",    "Left Orbit Arrow" },
  {  51, "lSkillShot3",        "Skill Shot 3" },
  {  52, "lLock1",             "Lock 1" },
  {  53, "lLock2",             "Lock 2" },
  {  54, "lLock3",             "Lock 3" },
  {  55, "lInnerLeftArrow",    "Inner Left Arrow" },
  {  56, "lAdvJackpot",        "Adv. Jackpot" },
  {  57, "lLDGLeftArrow",      "LDG Left Arrow" },
  {  58, "lLDGRightArrow",     "LDG Right Arrow" },
  {  61, "lCollectJackpot",    "Collect Jackpot" },
  {  62, "lRampArrow",         "Ramp Arrow" },
  {  63, "lNum2",              "2" },
  {  64, "lChicken",           "Chicken" },
  {  65, "lGasoline",          "Gasoline" },
  {  66, "l2X",                "2X" },
  {  67, "l5X",                "5X" },
  {  68, "l10X",               "10X" },
  {  91, "lStart",             "Start Button" },
  { 0 }
};

/* solenoid outputs: coils, GI strings, RGB channels and servos */
static const pinheck_name_t pinheck_rzspook_solenoid_names[] = {
  {  1, "sKnocker",    "Knocker" },
  {  2, "sShaker",     "Shaker" },
  {  3, "sUFlipHigh",  "Upper Flipper High" },
  {  4, "sVUK",        "VUK" },
  {  5, "sPost",       "Ball Stop (stop post, right inner orbit)" },
  {  6, "sRPop",       "Right Pop Bumper" },
  {  7, "sDrop",       "Drop Target (raise)" },
  {  8, "sUFlipLow",   "Upper Flipper Low" },
  {  9, "sLLPop",      "Lower Left Pop" },
  { 10, "sULPop",      "Upper Left Pop" },
  { 11, "sLUSling",    "Upper Left Sling" },
  { 12, "sLSling",     "Left Sling" },
  { 13, "sLFlipLow",   "Left Flipper Low" },
  { 14, "sLFlipHigh",  "Left Flipper High" },
  { 17, "sLaunch",     "Autoplunger" },
  { 18, "sLoad",       "Ball Load (trough)" },
  { 19, "sRFlipLow",   "Right Flipper Low" },
  { 20, "sRFlipHigh",  "Right Flipper High" },
  { 21, "sRSling",     "Right Sling" },
  { 22, "sRUSling",    "Upper Right Sling" },
  { 25, "sGI0",        "GI_0 (backbox)" },
  { 26, "sGI1",        "GI_1 (backbox)" },
  { 27, "sGI2",        "GI_2 (backbox)" },
  { 28, "sGI3",        "GI_3 (backbox)" },
  { 29, "sGI4",        "GI_4 (backbox)" },
  { 30, "sGI5",        "GI_5 (backbox)" },
  { 31, "sGI6",        "GI_6 (backbox)" },
  { 32, "sGI7",        "GI_7 (backbox)" },
  { 37, "sGI8",        "GI_8 (no wire on the chart)" },
  { 38, "sGI9",        "GI_9 bottom playfield GI 1" },
  { 39, "sGI10",       "GI_10 bottom playfield GI 2" },
  { 40, "sGI11",       "GI_11 red GI" },
  { 41, "sGI12",       "GI_12 purple flasher" },
  { 42, "sGI13",       "GI_13 red flasher" },
  { 43, "sGI14",       "GI_14 white GI" },
  { 44, "sGI15",       "GI_15 (no driver fitted)" },
  { 51, "sRGB1R",      "RGB1 red" },
  { 52, "sRGB1G",      "RGB1 green" },
  { 53, "sRGB1B",      "RGB1 blue" },
  { 54, "sRGB2R",      "RGB2 red" },
  { 55, "sRGB2G",      "RGB2 green" },
  { 56, "sRGB2B",      "RGB2 blue" },
  { 57, "sGate",       "Servo 0: Spaulding gate" },
  { 58, "sRobot",      "Servo 1: robot" },
  { 59, "sServo2",     "Servo 2" },
  { 60, "sServo3",     "Servo 3" },
  { 61, "sServo4",     "Servo 4" },
  { 62, "sLDGR",       "LDG light red" },
  { 63, "sLDGB",       "LDG light blue" },
  { 64, "sLDGG",       "LDG light green" },
  { 0 }
};

static const pinheck_name_t pinheck_jetsons_switch_names[] = {
  {   1, "swCoinDoor",  "Coin Door (closed)" },
  {   2, "swUser",      "Launch Button" },
  {   3, "swRFlip",     "Right Flipper" },
  {   4, "swLFlip",     "Left Flipper" },
  {   5, "swBack",      "Back" },
  {   6, "swEnter",     "Enter (menu)" },
  {   7, "swCoin",      "Coin Mech" },
  {   8, "swTilt",      "Tilt" },
  {  11, "swROrbit",    "Right Orbit" },
  {  12, "swCaptive",   "Captive Ball" },
  {  13, "swRLane",     "Right Lane" },
  {  14, "swMLane",     "Middle Lane" },
  {  15, "swLLane",     "Left Lane" },
  {  16, "swElroy",     "Elroy Loop" },
  {  18, "swKickout",   "Kickout Hole" },
  {  21, "swScoopSw",   "Scoop" },
  {  22, "swExtraBall", "Extra Ball" },
  {  23, "swLSling",    "Left Sling" },
  {  24, "swLInlane",   "Left Inlane" },
  {  25, "swLOutlane",  "Left Outlane" },
  {  26, "swLFlipEOS",  "Left Flipper EOS" },
  {  31, "swCTargetG",  "Center Target G" },
  {  32, "swCTargetE",  "Center Target E" },
  {  33, "swCTargetO",  "Center Target O" },
  {  34, "swLowerPop",  "Lower Pop" },
  {  35, "swLPop",      "Left Pop" },
  {  36, "swRPop",      "Right Pop" },
  {  41, "swRTargetR",  "Right Target R" },
  {  42, "swRTargetG",  "Right Target G" },
  {  43, "swRTargetE",  "Right Target E" },
  {  44, "swRSling",    "Right Sling" },
  {  45, "swRInlane",   "Right Inlane" },
  {  46, "swROutlane",  "Right Outlane" },
  {  51, "swShooter",   "Shooter Lane" },
  {  53, "swTrough2",   "Ball Trough 2" },
  {  54, "swTrough3",   "Ball Trough 3" },
  {  55, "swRFlipEOS",  "Right Flipper EOS" },
  {  56, "swLOrbit",    "Left Orbit" },
  {  92, "swTrough1",   "Trough Opto 1 (ball trough 1)" },
  {  93, "swTroughJam", "Trough Jam Opto" },
  {  94, "swStart",     "Start Button" },
  {  96, "swScoop",     "Scoop Opto" },
  { 112, "swLRFlip",    "Right Flipper button (reaches switch 3)" },
  { 114, "swLLFlip",    "Left Flipper button (reaches switch 4)" },
  { 0 }
};

static const pinheck_name_t pinheck_jetsons_lamp_names[] = {
  {  11, "lJ",                 "J" },
  {  12, "lA",                 "A" },
  {  13, "lExtraBall",         "Extra Ball" },
  {  14, "lLScoopArrow",       "Left Scoop Arrow" },
  {  15, "lLScoopS",           "Left Scoop S" },
  {  16, "lRosie",             "Rosie" },
  {  17, "lAstro",             "Astro" },
  {  18, "lJudy",              "Judy" },
  {  21, "lE",                 "E" },
  {  22, "lN",                 "N" },
  {  23, "lRTargetE",          "Right Target E" },
  {  24, "lRTargetG",          "Right Target G" },
  {  25, "lRTargetR",          "Right Target R" },
  {  26, "lOrbity",            "Orbity" },
  {  27, "lElroy",             "Elroy" },
  {  28, "lJane",              "Jane" },
  {  31, "lGeorge",            "George" },
  {  32, "lJetScreamer",       "Jet Screamer" },
  {  33, "lOrbitCityMB",       "Orbit City MB" },
  {  34, "lSpacelyCogswellMB", "Spacely vs Cogswell MB" },
  {  35, "lJetAgain",          "Jet Again" },
  {  41, "lAstroJ",            "Astro J" },
  {  42, "lLOrbitArrow",       "Left Orbit Arrow" },
  {  43, "lJudyJ",             "Judy J" },
  {  44, "lRampArrow",         "Ramp Arrow" },
  {  45, "lElroyJ",            "Elroy J" },
  {  46, "lElroyLoopArrow",    "Elroy Loop Arrow" },
  {  47, "lCTargetG",          "Center Target G" },
  {  48, "lCTargetE",          "Center Target E" },
  {  51, "lCTargetO",          "Center Target O" },
  {  52, "lJackpot",           "Jackpot" },
  {  53, "lKickoutC",          "Kickout C" },
  {  54, "lKickoutArrow",      "Kickout Arrow" },
  {  55, "lOrbityJ",           "Orbity J" },
  {  56, "lROrbitArrow",       "Right Orbit Arrow" },
  {  91, "lStart",             "Start Button" },
  { 0 }
};

static const pinheck_name_t pinheck_jetsons_solenoid_names[] = {
  {  1, "sKnocker",    "Knocker (option)" },
  {  2, "sShaker",     "Shaker (option)" },
  {  3, "sRFlipLow",   "Right Flipper Low" },
  {  4, "sRFlipHigh",  "Right Flipper High" },
  {  5, "sLoad",       "Ball Load (trough)" },
  {  6, "sLaunch",     "Ball Launch (autolauncher)" },
  {  7, "sLFlipHigh",  "Left Flipper High" },
  {  8, "sLFlipLow",   "Left Flipper Low" },
  {  9, "sScoop",      "Scoop" },
  { 10, "sLSling",     "Left Sling" },
  { 11, "sRSling",     "Right Sling" },
  { 17, "sPost",       "Up Post (ball stop)" },
  { 18, "sLowerPop",   "Lower Pop" },
  { 19, "sLPop",       "Left Pop" },
  { 20, "sKickout",    "Saucer Kick Out" },
  { 21, "sRPop",       "Right Pop" },
  { 25, "sGI0",        "GI_0 (no wire on the chart)" },
  { 26, "sGI1",        "GI_1 (no wire on the chart)" },
  { 27, "sGI2",        "GI_2 (no wire on the chart)" },
  { 28, "sGI3",        "GI_3 (no wire on the chart)" },
  { 29, "sGI4",        "GI_4 (no wire on the chart)" },
  { 30, "sGI5",        "GI_5 (no wire on the chart)" },
  { 31, "sGI6",        "GI_6 (no wire on the chart)" },
  { 32, "sGI7",        "GI_7 (no wire on the chart)" },
  { 37, "sGI8",        "GI_8 ramp flasher" },
  { 38, "sGI9",        "GI_9 scoop flasher" },
  { 39, "sGI10",       "GI_10 left GI" },
  { 40, "sGI11",       "GI_11 right GI" },
  { 41, "sGI12",       "GI_12 (no wire on the chart)" },
  { 42, "sGI13",       "GI_13 (no wire on the chart)" },
  { 43, "sGI14",       "GI_14 (no wire on the chart)" },
  { 44, "sGI15",       "GI_15 (no wire on the chart)" },
  { 51, "sRGB1R",      "RGB1 red" },
  { 52, "sRGB1G",      "RGB1 green" },
  { 53, "sRGB1B",      "RGB1 blue" },
  { 54, "sRGB2R",      "RGB2 red (follows the Orbitty)" },
  { 55, "sRGB2G",      "RGB2 green (follows the Orbitty)" },
  { 56, "sRGB2B",      "RGB2 blue (follows the Orbitty)" },
  { 57, "sOrbitty",    "Servo 0: Orbitty topper" },
  { 58, "sServo1",     "Servo 1 (held at 90 degrees)" },
  { 59, "sServo2",     "Servo 2" },
  { 60, "sServo3",     "Servo 3" },
  { 61, "sServo4",     "Servo 4" },
  { 62, "sExtR",       "External RGB red (not written)" },
  { 63, "sExtG",       "External RGB green (not written)" },
  { 64, "sExtB",       "External RGB blue (not written)" },
  { 0 }
};

#endif
